version: "3.9"

networks:
    wso2_network:
        driver: bridge

volumes:
    is_database:
    is_logs:
    fakesmtp_received:

services:
    identity-server:
        image: wso2/wso2is:7.0.0
        ports:
            - "9443:9443"
            - "9763:9763"
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-k",
                    "-f",
                    "https://localhost:9443/oauth2/token/.well-known/openid-configuration",
                ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        volumes:
            - ./conf/identity-server:/home/wso2carbon/wso2-config-volume
            - is_database:/home/wso2carbon/wso2is-7.0.0/repository/database/
            - is_logs/:/home/wso2carbon/wso2is-7.0.0/repository/logs/
        networks:
            - wso2_network
        depends_on:
            - email
    email:
        build:
            context: ./fakesmtp
            dockerfile: Dockerfile
        ports:
            - "9090:25"
        volumes:
            - fakesmtp_received:/output
        networks:
            - wso2_network
        profiles:
            - email-service
